# Generated by Django 4.1.3 on 2022-11-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='availabe',
        ),
    ]
