# Generated by Django 4.1.3 on 2022-12-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerseapp', '0002_alter_product_options_remove_product_availabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
